name: vk_api_groups
description: A sample command-line application with basic argument parsing.
version: 0.0.1

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.4.2
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
